apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  labels:
    app: postgresql
data:
  PGDATA: "/var/lib/postgresql/data/"
  POSTGRESQL_PORT_NUMBER: "5432"
  POSTGRESQL_VOLUME_DIR: "/data"
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRESQL_ENABLE_LDAP: "no"
  POSTGRESQL_ENABLE_TLS: "no"
  POSTGRESQL_LOG_HOSTNAME: "false"
  POSTGRESQL_LOG_CONNECTIONS: "false"
  POSTGRESQL_LOG_DISCONNECTIONS: "false"
  POSTGRESQL_PGAUDIT_LOG_CATALOG: "off"
  POSTGRESQL_CLIENT_MIN_MESSAGES: "error"
  POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "pgaudit"
  POSTGRES_DB: ${AIRFLOW_DB}
  POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-hl
  labels:
    app: postgresql
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.1-alpine3.16
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresql
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-db-config
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
